---
  - name: Cria usuario
    user:
      name: '{{ item }}'
      shell: /bin/bash
#      groups: '{{ grupo }}'
      append: yes
      password: '{{ senha }}'
      state: present
    with_items: '{{ user }}'    

  - name: Usuario SUDO
    lineinfile:
      dest: /etc/sudoers
      line: "{{ sudo }}" 
 
# tasks file for usuario
